apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-pv
spec:
  storageClassName: hostpath 
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/projects/Public-Projects/portfolio/jupyter/notebooks
    type: Directory
  
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  