apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: test-storage
      mountPath: /mnt/test
  volumes:
  - name: test-storage
    persistentVolumeClaim:
      claimName: jupyter-pvc
