apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/Projects/code/Public-Projects-main/Public-Projects-main/portfolio/jupyter/notebooks
    type: Directory
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-pvc
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
