name: Teste on PR

on: 
  pull_request: 
    branches:[master]

jobs: 
  test:
    name: Teste Infra on PR
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Hashicorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: IaC Apply
      env:
        COMMAND_IAC: terraform
      run: |
        cd infrastructure
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan



