
my_first_postgres_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      port: 5432
      user: postgres
      password: postgres
      dbname: postgres
      schema: public
