apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: wednesday-primary-cluster
  labels:
    app: wednesday-primary-cluster
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        tls: False
        type: nodeport
        configuration:
          bootstrap:
            nodePort: 32100
          brokers:
            - broker: 0
              advertisedHost: localhost
              advertisedPort: 31769        
    config:
      # offsets.topic.replication.factor: 3
      # transaction.state.log.replication.factor: 3
      # transaction.state.log.min.isr: 2
      # default.replication.factor: 3
      # min.insync.replicas: 2
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      log.message.format.version: "3.7"
      inter.broker.protocol.version: "3.7"
      
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
