apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wednesday-topic-ratings
  labels:
    strimzi.io/cluster: wednesday-primary-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    # key.converter: org.apache.kafka.connect.json.JsonConverter
    # value.converter: org.apache.kafka.connect.json.JsonConverter
    #key.converter.schemas.enable: true
    #value.converter.schemas.enable: true
    retention.ms: 7200000
    segment.bytes: 1073741824